# Generated by Django 5.2.16 on 2026-07-30 03:09

import apps.reservations.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0005_correct_hostaway_listing_identifiers"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingQuote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hostaway_listing_id", models.PositiveBigIntegerField(editable=False)),
                ("check_in", models.DateField()),
                ("check_out", models.DateField()),
                (
                    "nights",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "guests",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("total_price", models.DecimalField(decimal_places=4, max_digits=14)),
                ("components", models.JSONField(default=list)),
                (
                    "price_version",
                    models.PositiveSmallIntegerField(default=2, editable=False),
                ),
                ("signature", models.CharField(editable=False, max_length=64)),
                ("session_key_hash", models.CharField(editable=False, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "نشط"),
                            ("expired", "منتهي"),
                            ("consumed", "مستخدم"),
                            ("invalidated", "ملغى"),
                            ("price_changed", "تغير السعر"),
                            ("unavailable", "غير متاح"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("calculated_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("invalidated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking_quotes",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "عرض سعر",
                "verbose_name_plural": "عروض الأسعار",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookingIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_reference",
                    models.CharField(
                        default=apps.reservations.models.booking_intent_reference,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("check_in", models.DateField()),
                ("check_out", models.DateField()),
                ("nights", models.PositiveSmallIntegerField()),
                ("guests", models.PositiveSmallIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("total_price", models.DecimalField(decimal_places=4, max_digits=14)),
                ("guest_first_name", models.CharField(max_length=100)),
                ("guest_last_name", models.CharField(max_length=100)),
                ("guest_email", models.EmailField(max_length=254)),
                ("guest_phone", models.CharField(max_length=20)),
                ("guest_country_code", models.CharField(max_length=2)),
                ("special_requests", models.TextField(blank=True, max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("pending_revalidation", "بانتظار إعادة التحقق"),
                            ("awaiting_payment", "جاهز للدفع"),
                            ("price_changed", "تغير السعر"),
                            ("unavailable", "غير متاح"),
                            ("expired", "منتهي"),
                            ("cancelled", "ملغى"),
                            ("completed", "مكتمل"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("session_key_hash", models.CharField(editable=False, max_length=64)),
                ("terms_accepted_at", models.DateTimeField()),
                ("privacy_accepted_at", models.DateTimeField()),
                ("marketing_consent", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking_intents",
                        to="properties.property",
                    ),
                ),
                (
                    "quote",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking_intent",
                        to="reservations.bookingquote",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب حجز مبدئي",
                "verbose_name_plural": "طلبات الحجز المبدئية",
                "ordering": ["-created_at"],
                "permissions": [
                    ("view_bookingintent_pii", "Can view booking intent guest data"),
                    ("cancel_bookingintent", "Can cancel booking intents"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="bookingquote",
            index=models.Index(
                fields=["status", "expires_at"], name="reservation_status_9fb895_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingquote",
            index=models.Index(
                fields=["property", "status"], name="reservation_propert_33aa0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingquote",
            index=models.Index(
                fields=["created_at"], name="reservation_created_87b0a4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingquote",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_price__gte", 0)),
                name="booking_quote_total_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingquote",
            constraint=models.CheckConstraint(
                condition=models.Q(("check_out__gt", models.F("check_in"))),
                name="booking_quote_checkout_after_checkin",
            ),
        ),
        migrations.AddIndex(
            model_name="bookingintent",
            index=models.Index(
                fields=["status", "expires_at"], name="reservation_status_c30121_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingintent",
            index=models.Index(
                fields=["property", "status"], name="reservation_propert_7ec1ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingintent",
            index=models.Index(
                fields=["created_at"], name="reservation_created_29df0f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingintent",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_price__gte", 0)),
                name="booking_intent_total_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingintent",
            constraint=models.CheckConstraint(
                condition=models.Q(("check_out__gt", models.F("check_in"))),
                name="booking_intent_checkout_after_checkin",
            ),
        ),
    ]
