# Generated by Django 5.2.16 on 2026-07-30 03:44

import apps.reservations.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_correct_hostaway_listing_identifiers"),
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_reference",
                    models.CharField(
                        default=apps.reservations.models.reservation_reference,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "hostaway_reservation_id",
                    models.PositiveBigIntegerField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                (
                    "hostaway_listing_id",
                    models.PositiveBigIntegerField(
                        blank=True, editable=False, null=True
                    ),
                ),
                (
                    "hostaway_listing_map_id",
                    models.PositiveBigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "channel_id",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("direct_website", "الموقع المباشر"),
                            ("hostaway_manual", "Hostaway يدوي"),
                            ("external_channel", "قناة خارجية"),
                            ("unknown", "غير معروف"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                (
                    "normalized_status",
                    models.CharField(
                        choices=[
                            ("awaiting_payment", "بانتظار الدفع"),
                            ("ready_for_hostaway", "جاهز لـHostaway"),
                            ("create_pending", "إنشاء معلق"),
                            ("creating", "جارٍ الإنشاء"),
                            ("confirmed", "مؤكد"),
                            ("create_failed", "فشل الإنشاء"),
                            ("create_unknown", "نتيجة الإنشاء غير مؤكدة"),
                            ("sync_pending", "مزامنة معلقة"),
                            ("modified", "معدل"),
                            ("cancelled", "ملغى"),
                            ("unknown", "غير معروف"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                (
                    "hostaway_status",
                    models.CharField(blank=True, editable=False, max_length=100),
                ),
                (
                    "payment_status",
                    models.CharField(blank=True, editable=False, max_length=100),
                ),
                ("check_in", models.DateField()),
                ("check_out", models.DateField()),
                (
                    "nights",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "guests",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("total_price", models.DecimalField(decimal_places=4, max_digits=14)),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking_intent",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservation",
                        to="reservations.bookingintent",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "حجز محلي",
                "verbose_name_plural": "الحجوزات المحلية",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HostawayReservationOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("create_reservation", "إنشاء حجز"),
                            ("retrieve_reservation", "جلب حجز"),
                            ("reconcile_creation", "مصالحـة إنشاء"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                (
                    "request_fingerprint",
                    models.CharField(editable=False, max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prepared", "مجهزة"),
                            ("in_progress", "قيد التنفيذ"),
                            ("succeeded", "ناجحة"),
                            ("failed", "فشلت"),
                            ("unknown", "غير مؤكدة"),
                            ("blocked", "محظورة"),
                        ],
                        default="prepared",
                        max_length=20,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "hostaway_reservation_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("error_code", models.CharField(blank=True, max_length=100)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hostaway_operations",
                        to="reservations.reservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "عملية حجز Hostaway",
                "verbose_name_plural": "عمليات حجوزات Hostaway",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["normalized_status", "-created_at"],
                name="reservation_normali_f40193_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["property", "check_in"], name="reservation_propert_6b2f47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["source_type", "-created_at"],
                name="reservation_source__b0b04a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["last_synced_at"], name="reservation_last_sy_b08302_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("check_out__gt", models.F("check_in"))),
                name="reservation_checkout_after_checkin",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_price__gte", 0)),
                name="reservation_total_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("normalized_status", "confirmed"), _negated=True),
                    ("hostaway_reservation_id__isnull", False),
                    _connector="OR",
                ),
                name="reservation_confirmed_requires_hostaway_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("confirmed_at__isnull", True),
                    ("cancelled_at__isnull", True),
                    _connector="OR",
                ),
                name="reservation_not_confirmed_and_cancelled",
            ),
        ),
        migrations.AddIndex(
            model_name="hostawayreservationoperation",
            index=models.Index(
                fields=["status", "-created_at"], name="reservation_status_62d254_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hostawayreservationoperation",
            index=models.Index(
                fields=["reservation", "operation_type"],
                name="reservation_reserva_4eb16b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hostawayreservationoperation",
            index=models.Index(
                fields=["created_at"], name="reservation_created_ea2fb8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="hostawayreservationoperation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("operation_type", "create_reservation")),
                fields=("reservation",),
                name="one_create_operation_per_reservation",
            ),
        ),
    ]
