# Generated by Django 5.2.16 on 2026-07-30 04:18

import apps.reservations.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_reservation_hostawayreservationoperation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingModificationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_reference",
                    models.CharField(
                        default=apps.reservations.models.modification_request_reference,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("extend_stay", "تمديد الإقامة"),
                            ("change_dates", "تغيير التواريخ"),
                            ("change_guests", "تغيير عدد الضيوف"),
                            ("cancel_reservation", "طلب إلغاء"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("pending_revalidation", "بانتظار إعادة التحقق"),
                            ("awaiting_customer_approval", "بانتظار موافقة العميل"),
                            ("awaiting_payment", "بانتظار الدفع"),
                            ("pending_admin_approval", "بانتظار الإدارة"),
                            ("ready_for_hostaway", "جاهز لـHostaway"),
                            ("processing", "قيد التنفيذ"),
                            ("completed", "مكتمل"),
                            ("rejected", "مرفوض"),
                            ("expired", "منتهي"),
                            ("price_changed", "تغير السعر"),
                            ("unavailable", "غير متاح"),
                            ("failed", "فشل"),
                            ("unknown", "نتيجة غير مؤكدة"),
                        ],
                        default="draft",
                        max_length=40,
                    ),
                ),
                ("old_check_in", models.DateField()),
                ("old_check_out", models.DateField()),
                ("new_check_in", models.DateField(blank=True, null=True)),
                ("new_check_out", models.DateField(blank=True, null=True)),
                (
                    "old_guests",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "new_guests",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("old_total", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "new_total",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "price_difference",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("currency", models.CharField(max_length=3)),
                ("reason", models.CharField(blank=True, max_length=1000)),
                (
                    "quote_snapshot",
                    models.JSONField(blank=True, default=dict, editable=False),
                ),
                (
                    "idempotency_key",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("session_key_hash", models.CharField(editable=False, max_length=64)),
                (
                    "requested_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expires_at", models.DateTimeField()),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modification_requests",
                        to="reservations.reservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب تعديل حجز",
                "verbose_name_plural": "طلبات تعديل الحجوزات",
                "ordering": ["-requested_at"],
                "permissions": [
                    (
                        "approve_bookingmodificationrequest",
                        "Can approve modification requests",
                    ),
                    (
                        "reject_bookingmodificationrequest",
                        "Can reject modification requests",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HostawayModificationOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("update_dates", "تحديث التواريخ"),
                            ("extend_stay", "تمديد الإقامة"),
                            ("update_guests", "تحديث الضيوف"),
                            ("cancel_reservation", "إلغاء الحجز"),
                            ("reconcile_modification", "مصالحـة التعديل"),
                        ],
                        max_length=35,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                (
                    "request_fingerprint",
                    models.CharField(editable=False, max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prepared", "مجهزة"),
                            ("in_progress", "قيد التنفيذ"),
                            ("succeeded", "ناجحة"),
                            ("failed", "فشلت"),
                            ("unknown", "غير مؤكدة"),
                            ("blocked", "محظورة"),
                        ],
                        default="prepared",
                        max_length=20,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "hostaway_reservation_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("error_code", models.CharField(blank=True, max_length=100)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "modification_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hostaway_operations",
                        to="reservations.bookingmodificationrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "عملية تعديل Hostaway",
                "verbose_name_plural": "عمليات تعديل Hostaway",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="bookingmodificationrequest",
            index=models.Index(
                fields=["status", "expires_at"], name="reservation_status_e96450_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingmodificationrequest",
            index=models.Index(
                fields=["reservation", "status"], name="reservation_reserva_61b062_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingmodificationrequest",
            index=models.Index(
                fields=["request_type", "-requested_at"],
                name="reservation_request_06bc1d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bookingmodificationrequest",
            index=models.Index(
                fields=["created_at"], name="reservation_created_6c6fbe_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingmodificationrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("old_check_out__gt", models.F("old_check_in"))),
                name="modification_old_checkout_after_checkin",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingmodificationrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("new_check_in__isnull", True),
                    ("new_check_out__isnull", True),
                    ("new_check_out__gt", models.F("new_check_in")),
                    _connector="OR",
                ),
                name="modification_new_checkout_after_checkin",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingmodificationrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("old_total__gte", 0)),
                name="modification_old_total_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingmodificationrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("new_total__isnull", True), ("new_total__gte", 0), _connector="OR"
                ),
                name="modification_new_total_nonnegative",
            ),
        ),
        migrations.AddIndex(
            model_name="hostawaymodificationoperation",
            index=models.Index(
                fields=["status", "-created_at"], name="reservation_status_5a4035_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hostawaymodificationoperation",
            index=models.Index(
                fields=["modification_request", "operation_type"],
                name="reservation_modific_02c41b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="hostawaymodificationoperation",
            constraint=models.UniqueConstraint(
                fields=("modification_request", "operation_type"),
                name="one_modification_operation_per_type",
            ),
        ),
    ]
