# Generated by Django 5.2.16 on 2026-09-03 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0007_bookingintent_payment_verified_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookingintent",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("view_bookingintent_pii", "Can view booking intent guest data"),
                    ("cancel_bookingintent", "Can cancel booking intents"),
                ],
                "verbose_name": "Booking intent",
                "verbose_name_plural": "Booking intents",
            },
        ),
        migrations.AlterModelOptions(
            name="bookingmodificationrequest",
            options={
                "ordering": ["-requested_at"],
                "permissions": [
                    (
                        "approve_bookingmodificationrequest",
                        "Can approve modification requests",
                    ),
                    (
                        "reject_bookingmodificationrequest",
                        "Can reject modification requests",
                    ),
                ],
                "verbose_name": "Booking modification request",
                "verbose_name_plural": "Booking modification requests",
            },
        ),
        migrations.AlterModelOptions(
            name="bookingquote",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Booking quote",
                "verbose_name_plural": "Booking quotes",
            },
        ),
        migrations.AlterModelOptions(
            name="hostawaymodificationoperation",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Hostaway modification operation",
                "verbose_name_plural": "Hostaway modification operations",
            },
        ),
        migrations.AlterModelOptions(
            name="hostawayreservationoperation",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Hostaway booking operation",
                "verbose_name_plural": "Hostaway booking operations",
            },
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Local reservation",
                "verbose_name_plural": "Local reservations",
            },
        ),
    ]
