# Generated by Django 5.2.16 on 2026-09-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0008_alter_bookingintent_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingintent",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_revalidation", "Awaiting re-verification"),
                    ("awaiting_payment", "Ready for payment"),
                    ("payment_verified", "Payment verified"),
                    ("price_changed", "Price changed"),
                    ("unavailable", "Unavailable"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="bookingmodificationrequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("extend_stay", "Extend stay"),
                    ("change_dates", "Change dates"),
                    ("change_guests", "Change guest count"),
                    ("cancel_reservation", "Cancellation request"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="bookingmodificationrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_revalidation", "Awaiting re-verification"),
                    ("awaiting_customer_approval", "بانتظار موافقة العميل"),
                    ("awaiting_payment", "Awaiting payment"),
                    ("pending_admin_approval", "Awaiting administration"),
                    ("ready_for_hostaway", "Ready for Hostaway"),
                    ("processing", "In progress"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                    ("price_changed", "Price changed"),
                    ("unavailable", "Unavailable"),
                    ("failed", "Failure"),
                    ("unknown", "Result unconfirmed"),
                ],
                default="draft",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="bookingquote",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("expired", "Expired"),
                    ("consumed", "Used"),
                    ("invalidated", "Cancelled"),
                    ("price_changed", "Price changed"),
                    ("unavailable", "Unavailable"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="hostawaymodificationoperation",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("update_dates", "Update dates"),
                    ("extend_stay", "Extend stay"),
                    ("update_guests", "Update guests"),
                    ("cancel_reservation", "Cancel booking"),
                    ("reconcile_modification", "Modification reconciliation"),
                ],
                max_length=35,
            ),
        ),
        migrations.AlterField(
            model_name="hostawaymodificationoperation",
            name="status",
            field=models.CharField(
                choices=[
                    ("prepared", "Prepared"),
                    ("in_progress", "In progress"),
                    ("succeeded", "Successful"),
                    ("failed", "Failed"),
                    ("unknown", "Unconfirmed"),
                    ("blocked", "Blocked"),
                ],
                default="prepared",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="hostawayreservationoperation",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("create_reservation", "Create booking"),
                    ("retrieve_reservation", "Fetch booking"),
                    ("reconcile_creation", "Creation reconciliation"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="hostawayreservationoperation",
            name="status",
            field=models.CharField(
                choices=[
                    ("prepared", "Prepared"),
                    ("in_progress", "In progress"),
                    ("succeeded", "Successful"),
                    ("failed", "Failed"),
                    ("unknown", "Unconfirmed"),
                    ("blocked", "Blocked"),
                ],
                default="prepared",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="normalized_status",
            field=models.CharField(
                choices=[
                    ("awaiting_payment", "Awaiting payment"),
                    ("ready_for_hostaway", "Ready for Hostaway"),
                    ("create_pending", "Creation pending"),
                    ("creating", "Creating"),
                    ("confirmed", "Confirmed"),
                    ("create_failed", "Creation failed"),
                    ("create_unknown", "Creation result unconfirmed"),
                    ("sync_pending", "Sync pending"),
                    ("modified", "Modified"),
                    ("cancelled", "Cancelled"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("direct_website", "Live site"),
                    ("hostaway_manual", "Hostaway manual"),
                    ("external_channel", "External channel"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=30,
            ),
        ),
    ]
