# Generated by Django 5.2.16 on 2026-09-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0009_alter_bookingintent_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingmodificationrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_revalidation", "Awaiting re-verification"),
                    ("awaiting_customer_approval", "Awaiting customer approval"),
                    ("awaiting_payment", "Awaiting payment"),
                    ("pending_admin_approval", "Awaiting administration"),
                    ("ready_for_hostaway", "Ready for Hostaway"),
                    ("processing", "In progress"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                    ("price_changed", "Price changed"),
                    ("unavailable", "Unavailable"),
                    ("failed", "Failure"),
                    ("unknown", "Result unconfirmed"),
                ],
                default="draft",
                max_length=40,
            ),
        ),
    ]
