# Generated by Django 5.2.16 on 2026-09-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0010_alter_bookingmodificationrequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="normalized_status",
            field=models.CharField(
                choices=[
                    ("awaiting_payment", "Awaiting payment"),
                    ("ready_for_hostaway", "Ready for Hostaway"),
                    ("create_pending", "Creation pending"),
                    ("creating", "Creating"),
                    ("confirmed", "Confirmed"),
                    ("create_failed", "Creation failed"),
                    ("create_unknown", "Creation result unconfirmed"),
                    ("sync_pending", "Sync pending"),
                    ("modified", "Modified"),
                    ("cancelled", "Cancelled"),
                    ("pending", "Pending confirmation"),
                    ("inquiry", "Inquiry"),
                    ("declined", "Declined"),
                    ("expired", "Expired"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=30,
            ),
        ),
    ]
