# Generated by Django 5.2.16 on 2026-09-04 00:53

import apps.reservations.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0011_reservation_status_covers_every_hostaway_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CancellationPolicyTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "policy_code",
                    models.CharField(
                        help_text="Hostaway policy name, exactly as synced onto the property.",
                        max_length=60,
                    ),
                ),
                (
                    "min_hours_before_check_in",
                    models.PositiveIntegerField(
                        help_text="Applies when the cancellation happens at least this long before arrival."
                    ),
                ),
                (
                    "refund_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage of the stay total returned to the guest.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "refunds_cleaning_fee",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to keep the cleaning fee when this tier applies.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cancellation policy tier",
                "verbose_name_plural": "Cancellation policy tiers",
                "ordering": ["policy_code", "-min_hours_before_check_in"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("policy_code", "min_hours_before_check_in"),
                        name="one_tier_per_policy_window",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RefundObligation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_reference",
                    models.CharField(
                        default=apps.reservations.models.refund_obligation_reference,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("modification_decrease", "Price decreased after a change"),
                            ("cancellation", "Cancellation refund"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("due", "Due to the guest"),
                            ("transferred", "Transferred"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="due",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                (
                    "calculation",
                    models.JSONField(blank=True, default=dict, editable=False),
                ),
                ("transfer_reference", models.CharField(blank=True, max_length=100)),
                ("transferred_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "modification_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_obligations",
                        to="reservations.bookingmodificationrequest",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_obligations",
                        to="reservations.reservation",
                    ),
                ),
                (
                    "transferred_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settled_refund_obligations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Refund owed to a guest",
                "verbose_name_plural": "Refunds owed to guests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="reservation_status_bda828_idx",
                    ),
                    models.Index(
                        fields=["reservation", "status"],
                        name="reservation_reserva_24a576_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gte", 0)),
                        name="refund_obligation_amount_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "transferred"), _negated=True),
                            ("transferred_at__isnull", False),
                            _connector="OR",
                        ),
                        name="transferred_refund_records_when",
                    ),
                ],
            },
        ),
    ]
