# Generated by Django 5.2.16 on 2026-09-04

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0012_cancellation_policy_table_and_refund_obligations"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingquote",
            name="exchange_rate_snapshot",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="bookingquote",
            name="payment_amount_sar",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bookingquote",
            name="selected_display_currency",
            field=models.CharField(blank=True, editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name="bookingintent",
            name="exchange_rate_snapshot",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="bookingintent",
            name="payment_amount_sar",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bookingintent",
            name="selected_display_currency",
            field=models.CharField(blank=True, editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name="bookingmodificationrequest",
            name="payment_amount_sar",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingquote",
            constraint=models.CheckConstraint(
                condition=Q(payment_amount_sar__isnull=True)
                | Q(payment_amount_sar__gte=0),
                name="booking_quote_payment_sar_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingintent",
            constraint=models.CheckConstraint(
                condition=Q(payment_amount_sar__isnull=True)
                | Q(payment_amount_sar__gte=0),
                name="booking_intent_payment_sar_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingmodificationrequest",
            constraint=models.CheckConstraint(
                condition=Q(payment_amount_sar__isnull=True)
                | Q(payment_amount_sar__gte=0),
                name="modification_payment_sar_nonnegative",
            ),
        ),
    ]
