# Generated by Django 5.2.16 on 2026-09-16

import apps.reservations.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0019_property_trustindex_review_metrics"),
        ("reservations", "0013_multi_currency_payment_snapshots"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualBookingDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_reference",
                    models.CharField(
                        default=apps.reservations.models.manual_booking_draft_reference,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("check_in", models.DateField(editable=False)),
                ("check_out", models.DateField(editable=False)),
                (
                    "nights",
                    models.PositiveSmallIntegerField(
                        editable=False,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "guests",
                    models.PositiveSmallIntegerField(
                        editable=False,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("currency", models.CharField(editable=False, max_length=3)),
                (
                    "system_total_price",
                    models.DecimalField(decimal_places=4, editable=False, max_digits=14),
                ),
                ("final_total_price", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "payment_amount_sar",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "selected_display_currency",
                    models.CharField(blank=True, editable=False, max_length=3),
                ),
                (
                    "exchange_rate_snapshot",
                    models.JSONField(blank=True, default=dict, editable=False),
                ),
                (
                    "price_source",
                    models.CharField(
                        choices=[
                            ("system", "Hostaway live price"),
                            ("manual_override", "Manual price adjustment"),
                        ],
                        default="system",
                        editable=False,
                        max_length=20,
                    ),
                ),
                ("price_override_reason", models.TextField(blank=True, max_length=500)),
                ("guest_first_name", models.CharField(blank=True, max_length=100)),
                ("guest_last_name", models.CharField(blank=True, max_length=100)),
                ("guest_email", models.EmailField(blank=True, max_length=254)),
                ("guest_phone", models.CharField(blank=True, max_length=32)),
                ("special_requests", models.TextField(blank=True, max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("quoted", "Quoted"),
                            ("ready_for_payment", "Ready for payment"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="quoted",
                        max_length=30,
                    ),
                ),
                ("availability_checked_at", models.DateTimeField(editable=False)),
                ("expires_at", models.DateTimeField(editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_manual_booking_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manual_booking_drafts",
                        to="properties.property",
                    ),
                ),
                (
                    "quote",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manual_booking_draft",
                        to="reservations.bookingquote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manual booking draft",
                "verbose_name_plural": "Manual booking drafts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "expires_at"],
                        name="reservation_status_d00c3a_idx",
                    ),
                    models.Index(
                        fields=["property", "check_in"],
                        name="reservation_propert_e6e99d_idx",
                    ),
                    models.Index(
                        fields=["created_at"],
                        name="reservation_created_5fcc47_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("final_total_price__gte", 0)),
                        name="manual_booking_draft_final_total_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("system_total_price__gte", 0)),
                        name="manual_booking_draft_system_total_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("payment_amount_sar__isnull", True),
                            ("payment_amount_sar__gte", 0),
                            _connector="OR",
                        ),
                        name="manual_booking_draft_payment_sar_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("check_out__gt", models.F("check_in"))),
                        name="manual_booking_draft_checkout_after_checkin",
                    ),
                ],
            },
        ),
    ]
