# Generated by Django 5.2.16 on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0014_manualbookingdraft"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refundobligation",
            name="status",
            field=models.CharField(
                choices=[
                    ("due", "Due to the guest"),
                    ("processing", "Processing with payment provider"),
                    ("transferred", "Transferred"),
                    ("cancelled", "Cancelled"),
                ],
                default="due",
                max_length=20,
            ),
        ),
    ]
