# Generated by Django 5.2.16 on 2026-09-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_refundobligation_processing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualbookingdraft',
            name='status',
            field=models.CharField(choices=[('quoted', 'Quoted'), ('ready_for_payment', 'Ready for payment'), ('booked_awaiting_payment', 'Booked — awaiting payment'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='quoted', max_length=30),
        ),
    ]
