# Generated by Django 5.2.16 on 2026-09-03 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Email verified at"
                    ),
                ),
                (
                    "verification_sent_for",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="Address awaiting proof",
                    ),
                ),
                (
                    "verification_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verification sent at"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer profile",
                "verbose_name_plural": "Customer profiles",
            },
        ),
    ]
