# Generated by Django 5.2.16 on 2026-09-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_customer_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=32, verbose_name="Phone number"),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="residence_address_line1",
            field=models.CharField(blank=True, max_length=250, verbose_name="Residence address"),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="residence_city",
            field=models.CharField(blank=True, max_length=120, verbose_name="Residence city"),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="residence_country",
            field=models.CharField(blank=True, max_length=100, verbose_name="Residence country"),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="residence_postal_code",
            field=models.CharField(blank=True, max_length=32, verbose_name="Residence postal code"),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="residence_region",
            field=models.CharField(blank=True, max_length=120, verbose_name="Residence region"),
        ),
    ]
