# Generated by Django 5.2.16 on 2026-10-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customerprofile_contact_and_residence'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('ar', 'Arabic'), ('en', 'English'), ('fr', 'French')], max_length=2, verbose_name='Preferred language'),
        ),
    ]
