# Generated by Django 5.2.16 on 2026-07-29 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationSyncRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("hostaway_properties", "Hostaway properties"),
                            ("hostaway_reviews", "Hostaway reviews"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "قيد التشغيل"),
                            ("succeeded", "نجحت"),
                            ("partially_succeeded", "نجحت جزئيًا"),
                            ("failed", "فشلت"),
                        ],
                        max_length=30,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("fetched_count", models.PositiveIntegerField(default=0)),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("updated_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("error_summary", models.TextField(blank=True)),
                ("dry_run", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="integration_sync_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "تشغيل مزامنة",
                "verbose_name_plural": "سجل المزامنة",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["sync_type", "-started_at"],
                        name="integration_sync_ty_9ce003_idx",
                    ),
                    models.Index(
                        fields=["status", "-started_at"],
                        name="integration_status_b1cd25_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "running")),
                        fields=("sync_type",),
                        name="one_running_sync_per_type",
                    )
                ],
            },
        ),
    ]
