# Generated by Django 5.2.16 on 2026-07-30 03:44

import uuid
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HostawayWebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "external_event_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("event_type", models.CharField(max_length=100)),
                (
                    "hostaway_object_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "hostaway_reservation_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "deduplication_key",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("body_hash", models.CharField(editable=False, max_length=64)),
                ("sanitized_payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "مستلم"),
                            ("processing", "قيد المعالجة"),
                            ("processed", "معالج"),
                            ("ignored", "متجاهل"),
                            ("retryable", "قابل لإعادة المحاولة"),
                            ("failed", "فشل دائم"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "received_at",
                    models.DateTimeField(default=timezone.now),
                ),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "حدث Hostaway Webhook",
                "verbose_name_plural": "أحداث Hostaway Webhook",
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "next_retry_at"],
                        name="integration_status_8b2bfa_idx",
                    ),
                    models.Index(
                        fields=["event_type", "-received_at"],
                        name="integration_event_t_6c8fdc_idx",
                    ),
                    models.Index(
                        fields=["hostaway_reservation_id"],
                        name="integration_hostawa_1c4357_idx",
                    ),
                    models.Index(
                        fields=["received_at"], name="integration_receive_c0374e_idx"
                    ),
                ],
            },
        ),
    ]
