# Generated by Django 5.2.16 on 2026-09-03 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_hostawaywebhookevent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hostawaywebhookevent",
            options={
                "ordering": ["-received_at"],
                "verbose_name": "Hostaway webhook event",
                "verbose_name_plural": "Hostaway webhook events",
            },
        ),
        migrations.AlterModelOptions(
            name="integrationsyncrun",
            options={
                "ordering": ["-started_at"],
                "verbose_name": "Sync run",
                "verbose_name_plural": "Sync runs",
            },
        ),
    ]
