# Generated by Django 5.2.16 on 2026-09-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0003_alter_hostawaywebhookevent_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostawaywebhookevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "Received"),
                    ("processing", "Processing"),
                    ("processed", "Processed"),
                    ("ignored", "Ignored"),
                    ("retryable", "Retryable"),
                    ("failed", "Permanent failure"),
                ],
                default="received",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="integrationsyncrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "Running"),
                    ("succeeded", "Succeeded"),
                    ("partially_succeeded", "Partially succeeded"),
                    ("failed", "Failed"),
                ],
                max_length=30,
            ),
        ),
    ]
