# Generated by Django 5.2.16 on 2026-10-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_alter_hostawaywebhookevent_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationsyncrun',
            name='sync_type',
            field=models.CharField(choices=[('hostaway_properties', 'Hostaway properties'), ('hostaway_reviews', 'Hostaway reviews'), ('price_calendar', 'Daily price calendar'), ('trustindex_metrics', 'Daily Trustindex metrics'), ('website_reservations', 'Website reservation statuses')], max_length=40),
        ),
    ]
