# Generated by Django 5.2.16 on 2026-07-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hostaway_listing_id", models.PositiveBigIntegerField(unique=True)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("name_ar", models.CharField(max_length=200)),
                ("name_en", models.CharField(max_length=200)),
                ("description_ar", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True)),
                ("city_ar", models.CharField(max_length=120)),
                ("city_en", models.CharField(max_length=120)),
                ("country_code", models.CharField(max_length=2)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "وحدة",
                "verbose_name_plural": "الوحدات",
                "ordering": ["-is_featured", "name_ar"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "is_featured"],
                        name="properties__is_acti_ff7ef9_idx",
                    ),
                    models.Index(
                        fields=["city_en", "is_active"],
                        name="properties__city_en_6a4e4f_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("country_code__regex", "^[A-Za-z]{2}$")),
                        name="property_country_code_iso2",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("latitude__isnull", True),
                            models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                            _connector="OR",
                        ),
                        name="property_valid_latitude",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("longitude__isnull", True),
                            models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                            _connector="OR",
                        ),
                        name="property_valid_longitude",
                    ),
                ],
            },
        ),
    ]
