# Generated by Django 5.2.16 on 2026-07-29 23:45

import apps.properties.uploads
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_rename_hostaway_fields"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="property",
            name="properties__is_acti_ff7ef9_idx",
        ),
        migrations.RemoveIndex(
            model_name="property",
            name="properties__city_en_6a4e4f_idx",
        ),
        migrations.RenameField(
            model_name="property",
            old_name="is_active",
            new_name="hostaway_is_active",
        ),
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hostaway_amenity_id",
                    models.PositiveBigIntegerField(blank=True, null=True, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("name_ar", models.CharField(blank=True, max_length=255)),
                ("name_en", models.CharField(blank=True, max_length=255)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("icon_key", models.SlugField(blank=True, max_length=80)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "مرفق",
                "verbose_name_plural": "المرافق",
                "ordering": ["category", "name_ar", "name_en", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="PropertyAmenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("hostaway", "Hostaway"), ("local", "محلي")],
                        default="local",
                        max_length=20,
                    ),
                ),
                ("is_visible", models.BooleanField(default=True)),
                ("is_active_at_source", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "مرفق الوحدة",
                "verbose_name_plural": "مرافق الوحدات",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hostaway_image_id",
                    models.PositiveBigIntegerField(blank=True, null=True, unique=True),
                ),
                ("hostaway_url", models.URLField(blank=True, max_length=2048)),
                ("hostaway_caption", models.CharField(blank=True, max_length=500)),
                ("sync_key", models.CharField(blank=True, max_length=72)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to=apps.properties.uploads.property_image_upload_to,
                        validators=[apps.properties.uploads.validate_property_image],
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("hostaway", "Hostaway"), ("local", "محلية")],
                        default="local",
                        max_length=20,
                    ),
                ),
                ("title_ar", models.CharField(blank=True, max_length=255)),
                ("title_en", models.CharField(blank=True, max_length=255)),
                ("alt_text_ar", models.CharField(blank=True, max_length=255)),
                ("alt_text_en", models.CharField(blank=True, max_length=255)),
                ("caption_ar", models.CharField(blank=True, max_length=500)),
                ("caption_en", models.CharField(blank=True, max_length=500)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("hostaway_sort_order", models.PositiveIntegerField(default=0)),
                ("is_cover", models.BooleanField(default=False)),
                ("is_visible", models.BooleanField(default=True)),
                ("is_active_at_source", models.BooleanField(default=True)),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "صورة وحدة",
                "verbose_name_plural": "صور الوحدات",
                "ordering": ["sort_order", "hostaway_sort_order", "id"],
            },
        ),
        migrations.AlterModelOptions(
            name="property",
            options={
                "ordering": ["-is_featured", "sort_order", "name_ar", "id"],
                "verbose_name": "وحدة",
                "verbose_name_plural": "الوحدات",
            },
        ),
        migrations.RemoveConstraint(
            model_name="property",
            name="property_country_code_iso2",
        ),
        migrations.AddField(
            model_name="property",
            name="address",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="property",
            name="average_review_rating",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="bathrooms_number",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="bedrooms_number",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="beds_number",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="city",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="property",
            name="content_is_customized",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="country",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="property",
            name="currency_code",
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name="property",
            name="hostaway_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="property",
            name="hostaway_internal_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="property",
            name="hostaway_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="property",
            name="imported_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="property",
            name="person_capacity",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="property_type",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="public_address",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="property",
            name="room_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="property",
            name="seo_description_ar",
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name="property",
            name="seo_description_en",
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name="property",
            name="seo_title_ar",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="property",
            name="seo_title_en",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="property",
            name="short_description_ar",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AddField(
            model_name="property",
            name="short_description_en",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AddField(
            model_name="property",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="property",
            name="source_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="state",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="property",
            name="zipcode",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="property",
            name="city_ar",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="property",
            name="city_en",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="property",
            name="country_code",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="property",
            name="name_ar",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="property",
            name="name_en",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["is_visible", "hostaway_is_active", "-is_featured"],
                name="properties__is_visi_48b336_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["sort_order", "id"], name="properties__sort_or_a8ade0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["city", "hostaway_is_active"],
                name="properties__city_49937e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["country_code", "hostaway_is_active"],
                name="properties__country_fccf2d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["last_synced_at"], name="properties__last_sy_7a21b0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("country_code", ""),
                    ("country_code__regex", "^[A-Za-z]{2}$"),
                    _connector="OR",
                ),
                name="property_country_code_iso2",
            ),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("currency_code", ""),
                    ("currency_code__regex", "^[A-Za-z]{3}$"),
                    _connector="OR",
                ),
                name="property_currency_code_iso3",
            ),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("average_review_rating__isnull", True),
                    models.Q(
                        ("average_review_rating__gte", 0),
                        ("average_review_rating__lte", 10),
                    ),
                    _connector="OR",
                ),
                name="property_review_rating_0_10",
            ),
        ),
        migrations.AddIndex(
            model_name="amenity",
            index=models.Index(
                fields=["is_active", "category"], name="properties__is_acti_959218_idx"
            ),
        ),
        migrations.AddField(
            model_name="propertyamenity",
            name="amenity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_links",
                to="properties.amenity",
            ),
        ),
        migrations.AddField(
            model_name="propertyamenity",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_amenities",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="properties.property",
            ),
        ),
        migrations.AddIndex(
            model_name="propertyamenity",
            index=models.Index(
                fields=["property", "source", "is_visible", "is_active_at_source"],
                name="properties__propert_83f4f0_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="propertyamenity",
            constraint=models.UniqueConstraint(
                fields=("property", "amenity"), name="unique_property_amenity"
            ),
        ),
        migrations.AddIndex(
            model_name="propertyimage",
            index=models.Index(
                fields=["property", "source", "is_visible", "is_active_at_source"],
                name="properties__propert_46c9ef_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="propertyimage",
            index=models.Index(
                fields=["property", "sort_order"], name="properties__propert_7883bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertyimage",
            index=models.Index(
                fields=["property", "is_cover"], name="properties__propert_c2e6b6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="propertyimage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("hostaway_url", ""), _negated=True),
                    models.Q(("image", ""), _negated=True),
                    _connector="OR",
                ),
                name="property_image_has_url_or_file",
            ),
        ),
        migrations.AddConstraint(
            model_name="propertyimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_cover", True), ("is_visible", True)),
                fields=("property",),
                name="one_visible_cover_per_property",
            ),
        ),
        migrations.AddConstraint(
            model_name="propertyimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source", "hostaway")),
                fields=("property", "sync_key"),
                name="unique_hostaway_image_sync_key",
            ),
        ),
    ]
