# Generated by Django 5.2.16 on 2026-07-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_correct_hostaway_listing_identifiers"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="consecutive_missing_syncs",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="property",
            name="hostaway_listing_map_id_verification_source",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="property",
            name="hostaway_listing_map_id_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="publish_blockers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="property",
            name="source_missing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="visibility_management",
            field=models.CharField(
                choices=[("automatic", "تلقائي"), ("manual", "يدوي")],
                default="manual",
                max_length=12,
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["source_missing", "consecutive_missing_syncs"],
                name="properties__source__5b557c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["visibility_management", "is_visible"],
                name="properties__visibil_341e95_idx",
            ),
        ),
    ]
