# Generated by Django 5.2.16 on 2026-07-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_property_sync_automation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={
                "ordering": ["category", "name_ar", "name_en", "name_fr", "name", "id"],
                "verbose_name": "مرفق",
                "verbose_name_plural": "المرافق",
            },
        ),
        migrations.AddField(
            model_name="amenity",
            name="name_fr",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="property",
            name="city_fr",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="property",
            name="description_fr",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="property",
            name="name_fr",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="property",
            name="seo_description_fr",
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name="property",
            name="seo_title_fr",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="property",
            name="short_description_fr",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="alt_text_fr",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="caption_fr",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="title_fr",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
