# Generated by Django 5.2.16 on 2026-09-03 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0009_normalize_supported_cities"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={
                "ordering": ["category", "name_ar", "name_en", "name_fr", "name", "id"],
                "verbose_name": "Amenity",
                "verbose_name_plural": "Amenities",
            },
        ),
        migrations.AlterModelOptions(
            name="property",
            options={
                "ordering": ["-is_featured", "sort_order", "name_ar", "id"],
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
            },
        ),
        migrations.AlterModelOptions(
            name="propertyamenity",
            options={
                "ordering": ["sort_order", "id"],
                "verbose_name": "Property amenity",
                "verbose_name_plural": "Property amenities",
            },
        ),
        migrations.AlterModelOptions(
            name="propertyimage",
            options={
                "ordering": ["sort_order", "hostaway_sort_order", "id"],
                "verbose_name": "Property image",
                "verbose_name_plural": "Property images",
            },
        ),
    ]
