# Generated by Django 5.2.16 on 2026-09-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0010_alter_amenity_options_alter_property_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="visibility_management",
            field=models.CharField(
                choices=[("automatic", "Automatic"), ("manual", "Manual")],
                default="manual",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="propertyamenity",
            name="source",
            field=models.CharField(
                choices=[("hostaway", "Hostaway"), ("local", "Local")],
                default="local",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="propertyimage",
            name="source",
            field=models.CharField(
                choices=[("hostaway", "Hostaway"), ("local", "Local")],
                default="local",
                max_length=20,
            ),
        ),
    ]
