# Generated by Django 5.2.16 on 2026-09-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0011_alter_property_visibility_management_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyimage",
            name="is_city_hero",
            field=models.BooleanField(
                default=False, verbose_name="Represents its city on the home page"
            ),
        ),
        migrations.AddIndex(
            model_name="propertyimage",
            index=models.Index(
                fields=["property", "is_city_hero"],
                name="properties__propert_222ad7_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="propertyimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_city_hero", True), ("is_visible", True)),
                fields=("property",),
                name="one_visible_city_hero_per_property",
            ),
        ),
    ]
