# Generated by Django 5.2.16 on 2026-09-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0012_property_image_city_hero"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="allow_same_day_booking",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="cancellation_policy",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="property",
            name="check_in_time_start",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="check_out_time",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="instant_bookable",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="max_nights",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="min_nights",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="same_day_booking_lead_time_hours",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="time_zone_name",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
