# Generated by Django 5.2.16 on 2026-09-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0013_property_carries_hostaway_booking_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="house_rules_ar",
            field=models.TextField(blank=True, verbose_name="House rules"),
        ),
        migrations.AddField(
            model_name="property",
            name="house_rules_en",
            field=models.TextField(blank=True, verbose_name="House rules"),
        ),
        migrations.AddField(
            model_name="property",
            name="house_rules_fr",
            field=models.TextField(blank=True, verbose_name="House rules"),
        ),
    ]
