# Generated by Django 5.2.16 on 2026-09-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0014_stay_policy_display"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="indicative_currency",
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name="property",
            name="indicative_nightly_from",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Indicative nightly rate",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="indicative_priced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
