# Generated by Django 5.2.16 on 2026-09-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0015_indicative_nightly_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="public_location_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Show the location map"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="public_location_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Public map latitude",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="public_location_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Public map longitude",
            ),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("public_location_latitude__isnull", True),
                    models.Q(
                        ("public_location_latitude__gte", -90),
                        ("public_location_latitude__lte", 90),
                    ),
                    _connector="OR",
                ),
                name="property_valid_public_latitude",
            ),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("public_location_longitude__isnull", True),
                    models.Q(
                        ("public_location_longitude__gte", -180),
                        ("public_location_longitude__lte", 180),
                    ),
                    _connector="OR",
                ),
                name="property_valid_public_longitude",
            ),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("public_location_latitude__isnull", True),
                        ("public_location_longitude__isnull", True),
                    ),
                    models.Q(
                        ("public_location_latitude__isnull", False),
                        ("public_location_longitude__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="property_public_location_coordinate_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("public_location_enabled", False),
                    models.Q(
                        ("public_location_latitude__isnull", False),
                        ("public_location_longitude__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="property_enabled_public_location_has_coordinates",
            ),
        ),
    ]
