# Generated by Django 5.2.16 on 2026-09-05 10:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0015_indicative_nightly_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="NearbyPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ar", models.CharField(blank=True, max_length=160)),
                ("name_en", models.CharField(blank=True, max_length=160)),
                ("name_fr", models.CharField(blank=True, max_length=160)),
                ("distance_ar", models.CharField(blank=True, max_length=120)),
                ("distance_en", models.CharField(blank=True, max_length=120)),
                ("distance_fr", models.CharField(blank=True, max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Nearby place",
                "verbose_name_plural": "Nearby places",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="property",
            name="public_location_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Show an approximate public map"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="public_location_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Approximate map latitude",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="public_location_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Approximate map longitude",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="public_location_radius_m",
            field=models.PositiveSmallIntegerField(
                default=650,
                validators=[
                    django.core.validators.MinValueValidator(500),
                    django.core.validators.MaxValueValidator(800),
                ],
                verbose_name="Approximate area radius in metres",
            ),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("public_location_latitude__isnull", True),
                    models.Q(
                        ("public_location_latitude__gte", -90),
                        ("public_location_latitude__lte", 90),
                    ),
                    _connector="OR",
                ),
                name="property_valid_public_latitude",
            ),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("public_location_longitude__isnull", True),
                    models.Q(
                        ("public_location_longitude__gte", -180),
                        ("public_location_longitude__lte", 180),
                    ),
                    _connector="OR",
                ),
                name="property_valid_public_longitude",
            ),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("public_location_radius_m__gte", 500),
                    ("public_location_radius_m__lte", 800),
                ),
                name="property_public_radius_500_800m",
            ),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("public_location_enabled", False),
                    models.Q(
                        ("public_location_latitude__isnull", False),
                        ("public_location_longitude__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="property_public_map_has_centre",
            ),
        ),
        migrations.AddField(
            model_name="nearbyplace",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nearby_places",
                to="properties.property",
            ),
        ),
        migrations.AddIndex(
            model_name="nearbyplace",
            index=models.Index(
                fields=["property", "is_active", "sort_order"],
                name="properties__propert_643bba_idx",
            ),
        ),
    ]
