# Generated by Django 5.2.16 on 2026-07-30 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SitePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("title_ar", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200)),
                ("body_ar", models.TextField(blank=True)),
                ("body_en", models.TextField(blank=True)),
                ("meta_description_ar", models.CharField(blank=True, max_length=320)),
                ("meta_description_en", models.CharField(blank=True, max_length=320)),
                ("is_published", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "صفحة محتوى",
                "verbose_name_plural": "صفحات المحتوى",
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="Luxury Smart Apartments", max_length=120),
                ),
                ("tagline_ar", models.CharField(blank=True, max_length=240)),
                ("tagline_en", models.CharField(blank=True, max_length=240)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=30)),
                ("whatsapp_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("office_hours_ar", models.CharField(blank=True, max_length=200)),
                ("office_hours_en", models.CharField(blank=True, max_length=200)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "إعداد الموقع",
                "verbose_name_plural": "إعدادات الموقع",
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("subject", models.CharField(max_length=200)),
                (
                    "message",
                    models.TextField(
                        validators=[django.core.validators.MaxLengthValidator(2000)]
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("ar", "العربية"), ("en", "English")], max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جديدة"),
                            ("in_progress", "قيد المتابعة"),
                            ("closed", "مغلقة"),
                            ("spam", "مزعجة"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "رسالة تواصل",
                "verbose_name_plural": "رسائل التواصل",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="core_contac_status_a0adbc_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="core_contac_created_25856d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FAQItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_ar", models.CharField(max_length=300)),
                ("question_en", models.CharField(max_length=300)),
                ("answer_ar", models.TextField()),
                ("answer_en", models.TextField()),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "سؤال شائع",
                "verbose_name_plural": "الأسئلة الشائعة",
                "ordering": ["sort_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "sort_order"],
                        name="core_faqite_is_acti_20bc53_idx",
                    )
                ],
            },
        ),
    ]
