# Generated by Django 5.2.16 on 2026-07-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_seed_public_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="brand_name_ar",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="brand_name_en",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="facebook_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="footer_text_ar",
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="footer_text_en",
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="public_address_ar",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="public_address_en",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="whatsapp_display_number",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="x_url",
            field=models.URLField(blank=True),
        ),
    ]
