# Generated by Django 5.2.16 on 2026-07-30 23:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_sitesetting_brand_name_ar_sitesetting_brand_name_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegacyRedirect",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_path", models.CharField(max_length=500, unique=True)),
                ("destination_path", models.CharField(blank=True, max_length=500)),
                (
                    "redirect_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (301, "301 Permanent"),
                            (302, "302 Temporary"),
                            (410, "410 Gone"),
                        ],
                        default=301,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "hit_count",
                    models.PositiveBigIntegerField(default=0, editable=False),
                ),
                (
                    "last_hit_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "تحويل رابط قديم",
                "verbose_name_plural": "تحويلات الروابط القديمة",
                "ordering": ["source_path"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "source_path"],
                        name="core_legacy_is_acti_f71cdd_idx",
                    ),
                    models.Index(
                        fields=["redirect_type", "is_active"],
                        name="core_legacy_redirec_141e56_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MarketingEventReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        choices=[("purchase", "Purchase"), ("refund", "Refund")],
                        max_length=20,
                    ),
                ),
                ("object_type", models.CharField(max_length=80)),
                (
                    "object_reference_hash",
                    models.CharField(editable=False, max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prepared", "مجهز"),
                            ("emitted", "أرسل"),
                            ("blocked", "محظور"),
                        ],
                        default="prepared",
                        max_length=20,
                    ),
                ),
                ("emitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "إيصال حدث تسويقي",
                "verbose_name_plural": "إيصالات الأحداث التسويقية",
                "ordering": ["-created_at"],
                "permissions": [
                    ("view_marketing_diagnostics", "Can view marketing diagnostics"),
                    ("view_seo_dashboard", "Can view SEO dashboard"),
                ],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="core_market_status_1b5467_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event_name", "object_reference_hash"),
                        name="unique_financial_marketing_event",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("event_name__in", ("purchase", "refund"))),
                        name="marketing_receipt_financial_events_only",
                    ),
                ],
            },
        ),
    ]
