# Generated by Django 5.2.16 on 2026-07-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_seed_confirmed_legacy_redirects"),
    ]

    operations = [
        migrations.AddField(
            model_name="faqitem",
            name="answer_fr",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="faqitem",
            name="question_fr",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="sitepage",
            name="body_fr",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sitepage",
            name="meta_description_fr",
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name="sitepage",
            name="title_fr",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="brand_name_fr",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="footer_text_fr",
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="office_hours_fr",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="public_address_fr",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="tagline_fr",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="language",
            field=models.CharField(
                choices=[("ar", "العربية"), ("en", "English"), ("fr", "Français")],
                max_length=10,
            ),
        ),
    ]
