# Generated by Django 5.2.16 on 2026-09-03 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_refresh_booking_faq"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactmessage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Contact message",
                "verbose_name_plural": "Contact messages",
            },
        ),
        migrations.AlterModelOptions(
            name="faqitem",
            options={
                "ordering": ["sort_order", "id"],
                "verbose_name": "FAQ item",
                "verbose_name_plural": "FAQ items",
            },
        ),
        migrations.AlterModelOptions(
            name="legacyredirect",
            options={
                "ordering": ["source_path"],
                "verbose_name": "Legacy redirect",
                "verbose_name_plural": "Legacy redirects",
            },
        ),
        migrations.AlterModelOptions(
            name="marketingeventreceipt",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("view_marketing_diagnostics", "Can view marketing diagnostics"),
                    ("view_seo_dashboard", "Can view SEO dashboard"),
                ],
                "verbose_name": "Marketing event receipt",
                "verbose_name_plural": "Marketing event receipts",
            },
        ),
        migrations.AlterModelOptions(
            name="sitepage",
            options={
                "ordering": ["slug"],
                "verbose_name": "Content page",
                "verbose_name_plural": "Content pages",
            },
        ),
        migrations.AlterModelOptions(
            name="sitesetting",
            options={
                "verbose_name": "Site setting",
                "verbose_name_plural": "Site settings",
            },
        ),
    ]
