# Generated by Django 5.2.16 on 2026-09-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_contactmessage_options_alter_faqitem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in_progress", "Being followed up"),
                    ("closed", "Closed"),
                    ("spam", "Spam"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="marketingeventreceipt",
            name="status",
            field=models.CharField(
                choices=[
                    ("prepared", "Prepared"),
                    ("emitted", "Sent"),
                    ("blocked", "Blocked"),
                ],
                default="prepared",
                max_length=20,
            ),
        ),
    ]
