# Generated by Django 5.2.16 on 2026-09-04 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_contactmessage_status_and_more"),
        ("properties", "0013_property_carries_hostaway_booking_policy"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faqitem",
            options={
                "ordering": ["category", "sort_order", "id"],
                "verbose_name": "FAQ item",
                "verbose_name_plural": "FAQ items",
            },
        ),
        migrations.AddField(
            model_name="faqitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("booking", "Booking and payment"),
                    ("stay", "During your stay"),
                    ("policy", "Policies and cancellation"),
                    ("property", "About the property"),
                ],
                default="booking",
                max_length=20,
                verbose_name="Category",
            ),
        ),
        migrations.AddField(
            model_name="faqitem",
            name="property",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave empty for a question that applies to every stay.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faq_items",
                to="properties.property",
                verbose_name="Specific property",
            ),
        ),
        migrations.AddIndex(
            model_name="faqitem",
            index=models.Index(
                fields=["property", "is_active"], name="core_faqite_propert_31e49e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="faqitem",
            index=models.Index(
                fields=["category", "sort_order"], name="core_faqite_categor_01acdb_idx"
            ),
        ),
    ]
