# Generated by Django 5.2.16 on 2026-09-04 01:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_contactmessage_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="default_check_in_hour",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Used when Hostaway reports no check-in time for a property.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(24),
                ],
                verbose_name="Default check-in hour",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="default_check_out_hour",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Used when Hostaway reports no check-out time for a property.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(24),
                ],
                verbose_name="Default check-out hour",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="default_house_rules_ar",
            field=models.TextField(blank=True, verbose_name="Default house rules"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="default_house_rules_en",
            field=models.TextField(blank=True, verbose_name="Default house rules"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="default_house_rules_fr",
            field=models.TextField(blank=True, verbose_name="Default house rules"),
        ),
    ]
