# Generated by Django 5.2.16 on 2026-09-05 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_faq_categories_and_property_scope"),
        ("core", "0013_stay_policy_display"),
    ]

    operations = []
