# Generated by Django 5.2.16 on 2026-09-05 14:45

import apps.core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_merge_20260905_0300"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteInterfaceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("home_hero", "Home hero backdrop"),
                            ("home_marrakech_postcard", "Home Marrakech postcard"),
                            ("home_riyadh_destination", "Home Riyadh destination"),
                            (
                                "home_marrakech_destination",
                                "Home Marrakech destination",
                            ),
                            ("home_story", "Home story image"),
                            ("home_final_cta", "Home final call to action"),
                        ],
                        help_text="Each placement can have one managed image.",
                        max_length=40,
                        unique=True,
                        verbose_name="Interface placement",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="JPEG, PNG, or WebP; maximum 10 MB.",
                        upload_to=apps.core.uploads.site_interface_image_upload_to,
                        validators=[apps.core.uploads.validate_site_interface_image],
                        verbose_name="Image",
                    ),
                ),
                (
                    "alt_text_ar",
                    models.CharField(
                        blank=True, max_length=240, verbose_name="Arabic alt text"
                    ),
                ),
                (
                    "alt_text_en",
                    models.CharField(
                        blank=True, max_length=240, verbose_name="English alt text"
                    ),
                ),
                (
                    "alt_text_fr",
                    models.CharField(
                        blank=True, max_length=240, verbose_name="French alt text"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Inactive images remain saved but are not shown publicly.",
                        verbose_name="Active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Interface image",
                "verbose_name_plural": "Interface images",
                "ordering": ["placement"],
            },
        ),
    ]
