# Generated by Django 5.2.16 on 2026-10-05 18:38

from django.db import migrations, models


def seed_business_profiles(apps, schema_editor):
    """Fill missing links verified from the connected business profiles on 2026-10-05."""
    site_setting = apps.get_model("core", "SiteSetting")
    manager = site_setting.objects.using(schema_editor.connection.alias)
    for field, url in {
        "instagram_url": "https://www.instagram.com/luxury_smart_apartments/",
        "facebook_url": "https://www.facebook.com/Luxury.Home23",
        "tiktok_url": "https://www.tiktok.com/@luxury_smart_apartments",
        "x_url": "https://x.com/LuxurySmartApts",
        "youtube_url": "https://www.youtube.com/channel/UCJYJpDWsyYVqb8zagf2Zjeg",
        "linkedin_url": "https://www.linkedin.com/company/luxurysmartapartments/",
        "snapchat_url": "https://www.snapchat.com/@luxurysmartapts",
    }.items():
        # Do not replace links the owner already configured in the dashboard.
        manager.filter(**{field: ""}).update(**{field: url})


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_irqah_legacy_listing_redirect"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="snapchat_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="tiktok_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="youtube_url",
            field=models.URLField(blank=True),
        ),
        migrations.RunPython(seed_business_profiles, migrations.RunPython.noop),
    ]
