# Generated by Django 5.2.16 on 2026-07-30 03:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider", models.CharField(max_length=50)),
                (
                    "provider_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=14)),
                ("currency", models.CharField(max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "منشأة"),
                            ("pending", "قيد المعالجة"),
                            ("succeeded", "ناجحة"),
                            ("failed", "فاشلة"),
                            ("cancelled", "ملغاة"),
                            ("expired", "منتهية"),
                            ("refunded", "مستردة"),
                            ("partially_refunded", "مستردة جزئيًا"),
                        ],
                        default="created",
                        max_length=30,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=64, unique=True)),
                ("failure_code", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "محاولة دفع",
                "verbose_name_plural": "محاولات الدفع",
                "ordering": ["-created_at"],
            },
        ),
    ]
