# Generated by Django 5.2.16 on 2026-07-30 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0001_initial"),
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentattempt",
            name="booking_intent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_attempts",
                to="reservations.bookingintent",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentattempt",
            index=models.Index(
                fields=["booking_intent", "status"],
                name="payments_pa_booking_704700_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentattempt",
            index=models.Index(
                fields=["provider", "provider_reference"],
                name="payments_pa_provide_dfbc5d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentattempt",
            index=models.Index(
                fields=["created_at"], name="payments_pa_created_e831f4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="payment_attempt_amount_nonnegative",
            ),
        ),
    ]
