# Generated by Django 5.2.16 on 2026-09-03 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_backfill_verified_booking_state"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentattempt",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Payment attempt",
                "verbose_name_plural": "Payment attempts",
            },
        ),
    ]
