# Generated by Django 5.2.16 on 2026-09-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_alter_paymentattempt_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentattempt",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("pending", "Processing"),
                    ("succeeded", "Successful"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                    ("refunded", "Refunded"),
                    ("partially_refunded", "Partially refunded"),
                    ("review", "Needs review"),
                    ("unknown", "Unknown"),
                ],
                default="created",
                max_length=30,
            ),
        ),
    ]
