# Generated by Django 5.2.16 on 2026-09-04

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_alter_paymentattempt_status"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.CheckConstraint(
                condition=~Q(provider="hyperpay") | Q(currency="SAR"),
                name="hyperpay_payment_currency_sar",
            ),
        ),
    ]
