# Generated by Django 5.2.16 on 2026-10-04 17:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_hyperpay_sar_constraint'),
        ('reservations', '0017_alter_bookingmodificationrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HyperBillWebhookSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HyperBillInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_reference', models.CharField(max_length=32, unique=True)),
                ('invoice_no', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('payment_url', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(default='creating', max_length=30)),
                ('delivery_status', models.CharField(default='not_sent', max_length=30)),
                ('delivery_message_id', models.CharField(blank=True, max_length=255)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hyperbill_invoice', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='hyperbill_amount_positive'), models.CheckConstraint(condition=models.Q(('currency', 'SAR')), name='hyperbill_currency_sar')],
            },
        ),
    ]
