# Generated by Django 5.2.16 on 2026-10-01 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_hyperpay_sar_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentattempt',
            name='payment_brand',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.CreateModel(
            name='HostawayFinancialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('posting', 'Posting'), ('succeeded', 'Recorded'), ('unknown', 'Unknown outcome'), ('review', 'Needs accounting review')], default='pending', max_length=20)),
                ('remote_charge_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_attempt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hostaway_receipt', to='payments.paymentattempt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
