"""Seed a small, safe catalogue into the owned Render preview.

This command is deliberately local-only: it makes no HTTP requests and creates
no reservations, payments, reviews, emails, or channel-manager changes.
"""

from typing import Any

from django.core.management.base import BaseCommand
from django.db import transaction

from apps.properties.models import Property, PropertyImage


LISTINGS: tuple[dict[str, Any], ...] = (
    {
        "id": 315814,
        "slug": "spacious-and-modern-apartment-for-rent-in-riyadh",
        "city": "Riyadh",
        "country": "Saudi Arabia",
        "country_code": "SA",
        "currency": "SAR",
        "capacity": 7,
        "bedrooms": 3,
        "beds": 6,
        "bathrooms": "3.0",
        "rating": "9.7",
        "name_ar": "شقة ذكية فسيحة بثلاث غرف نوم في عرقة",
        "name_en": "Spacious Three-Bedroom Smart Apartment in Irqah",
        "name_fr": "Grand appartement intelligent de trois chambres à Irqah",
        "short_ar": "شقة ذكية عائلية في عرقة، مع موقف خاص وإنترنت ودخول ذاتي.",
        "short_en": "A family-friendly smart stay in Irqah with parking, Wi-Fi and self check-in.",
        "short_fr": "Un séjour intelligent familial à Irqah, avec parking, Wi-Fi et arrivée autonome.",
        "image_id": 337265857,
        "image_url": "https://hostaway-platform.s3.us-west-2.amazonaws.com/listing/125670-315814-g74Wo6h-79E8aqdVM-5Zy-598-9Y5j7fhpvRVteLPR4-6a1f2583a1661",
        "city_hero": True,
    },
    {
        "id": 315815,
        "slug": "darat-safa-luxury-apartment",
        "city": "Riyadh",
        "country": "Saudi Arabia",
        "country_code": "SA",
        "currency": "SAR",
        "capacity": 6,
        "bedrooms": 3,
        "beds": 5,
        "bathrooms": "3.0",
        "rating": "9.4",
        "name_ar": "شقة درة صفا الفاخرة في الملقا",
        "name_en": "Darat Safa Luxury Apartment in Al Malqa",
        "name_fr": "Appartement Darat Safa de luxe à Al Malqa",
        "short_ar": "شقة ذكية هادئة في الملقا ضمن مبنى حديث ومجهز.",
        "short_en": "A calm smart apartment in Al Malqa within a modern, well-equipped building.",
        "short_fr": "Un appartement intelligent et paisible à Al Malqa, dans un immeuble moderne.",
        "image_id": 315310253,
        "image_url": "https://hostaway-platform.s3.us-west-2.amazonaws.com/listing/125670-315815-b9WvhOV3k0450gpDdeyZMVbaPBDGQi9nYJIT6uML6Vo-676e911b44ba2",
        "city_hero": False,
    },
    {
        "id": 315816,
        "slug": "luxury-smart-apartment-e12",
        "city": "Riyadh",
        "country": "Saudi Arabia",
        "country_code": "SA",
        "currency": "SAR",
        "capacity": 4,
        "bedrooms": 2,
        "beds": 2,
        "bathrooms": "3.0",
        "rating": "9.8",
        "name_ar": "شقة Luxury Living الذكية E12",
        "name_en": "Luxury Living Smart Apartment E12",
        "name_fr": "Appartement intelligent Luxury Living E12",
        "short_ar": "إقامة ذكية أنيقة مع موقف داخلي وإنترنت ودخول خاص برمز.",
        "short_en": "An elegant smart stay with indoor parking, Wi-Fi and private code entry.",
        "short_fr": "Un séjour intelligent élégant avec parking intérieur, Wi-Fi et accès par code.",
        "image_id": 315310360,
        "image_url": "https://hostaway-platform.s3.us-west-2.amazonaws.com/listing/125670-315816-BQOnX2P67a-uJg1WyCVap14o6oD-BnejIgaWvuQp6nM-676e910e34d0d",
        "city_hero": False,
    },
    {
        "id": 325731,
        "slug": "al-hamra-family-villa",
        "city": "Riyadh",
        "country": "Saudi Arabia",
        "country_code": "SA",
        "currency": "SAR",
        "capacity": 9,
        "bedrooms": 4,
        "beds": 8,
        "bathrooms": "3.0",
        "rating": "9.6",
        "name_ar": "فيلا الحمراء العائلية",
        "name_en": "Al Hamra Family Villa",
        "name_fr": "Villa familiale Al Hamra",
        "short_ar": "فيلا عائلية واسعة في الحمراء، مناسبة للمجموعات والإقامات الهادئة.",
        "short_en": "A spacious Al Hamra villa for families, groups and relaxed stays.",
        "short_fr": "Une villa spacieuse à Al Hamra, pour familles, groupes et séjours sereins.",
        "image_id": 315309931,
        "image_url": "https://hostaway-platform.s3.us-west-2.amazonaws.com/listing/125670-325731-nNIHbLSGbtK3Zvrv6InTy3fHoqdK7g4Mm3zEiAIt7WA-676e83318df8e",
        "city_hero": False,
    },
    {
        "id": 325961,
        "slug": "luxury-smart-apartment-a11",
        "city": "Riyadh",
        "country": "Saudi Arabia",
        "country_code": "SA",
        "currency": "SAR",
        "capacity": 6,
        "bedrooms": 3,
        "beds": 5,
        "bathrooms": "3.0",
        "rating": "9.7",
        "name_ar": "شقة Luxury Living الذكية A11",
        "name_en": "Luxury Living Smart Apartment A11",
        "name_fr": "Appartement intelligent Luxury Living A11",
        "short_ar": "شقة ذكية بثلاث غرف نوم في شرق الرياض، عملية ومريحة للعائلات.",
        "short_en": "A practical, comfortable three-bedroom smart apartment in east Riyadh.",
        "short_fr": "Un appartement intelligent pratique et confortable de trois chambres à l'est de Riyad.",
        "image_id": 315310019,
        "image_url": "https://hostaway-platform.s3.us-west-2.amazonaws.com/listing/125670-325961-NKD1nOnBp7s29QW--XIwtkMmC8s9PMOr3RkY--qDnnN8-676e82e361bbf",
        "city_hero": False,
    },
    {
        "id": 343666,
        "slug": "luxury-smart-apartment-b12",
        "city": "Riyadh",
        "country": "Saudi Arabia",
        "country_code": "SA",
        "currency": "SAR",
        "capacity": 7,
        "bedrooms": 3,
        "beds": 6,
        "bathrooms": "3.0",
        "rating": "9.8",
        "name_ar": "شقة Luxury Living الذكية B12 في المونسية",
        "name_en": "Luxury Living Smart Apartment B12 in Al Munsiyah",
        "name_fr": "Appartement intelligent Luxury Living B12 à Al Munsiyah",
        "short_ar": "شقة ذكية واسعة بثلاث غرف نوم في المونسية، مع تلفاز كبير وموقف خاص.",
        "short_en": "A spacious three-bedroom smart apartment in Al Munsiyah with a large TV and private parking.",
        "short_fr": "Un spacieux appartement intelligent de trois chambres à Al Munsiyah, avec grand téléviseur et parking privé.",
        "image_id": 328846427,
        "image_url": "https://hostaway-platform.s3.us-west-2.amazonaws.com/listing/125670-343666--yoK4Mm4vSUNFhq4iiF4uBZdYFViDTyoGU4AjooOYsg-689c1c3917a15",
        "city_hero": False,
    },
    {
        "id": 511786,
        "slug": "luxury-smart-apartment-at-nour-prestige-marrakech",
        "city": "Marrakesh",
        "country": "Morocco",
        "country_code": "MA",
        "currency": "MAD",
        "capacity": 6,
        "bedrooms": 3,
        "beds": 5,
        "bathrooms": "3.0",
        "rating": "10.0",
        "name_ar": "شقة Luxury Living الذكية في نور بريستيج، مراكش",
        "name_en": "Luxury Living Smart Apartment at Nour Prestige Marrakech",
        "name_fr": "Appartement intelligent Luxury Living au Nour Prestige Marrakech",
        "short_ar": "شقة ذكية عائلية في نور بريستيج بمراكش، قريبة من حديقة ماجوريل.",
        "short_en": "A family-friendly smart apartment at Nour Prestige Marrakech near Jardin Majorelle.",
        "short_fr": "Un appartement intelligent familial au Nour Prestige Marrakech, près du Jardin Majorelle.",
        "image_id": 335481813,
        "image_url": "https://hostaway-platform.s3.us-west-2.amazonaws.com/listing/125670-511786-67faa18eNPJAhhnjB3KvNjM9u4oMu9u3KB8MnWmCyTE-69e8804d2783b",
        "city_hero": True,
    },
)


class Command(BaseCommand):
    help = "Seed the safe Render staging catalogue without external integrations."

    @transaction.atomic
    def handle(self, *args: object, **options: Any) -> None:
        created_properties = created_images = 0
        for index, listing in enumerate(LISTINGS, start=1):
            property_obj, created = Property.objects.update_or_create(
                hostaway_listing_id=listing["id"],
                defaults={
                    "hostaway_name": listing["name_en"],
                    "hostaway_description": listing["short_en"],
                    "room_type": "entire_home",
                    "person_capacity": listing["capacity"],
                    "bedrooms_number": listing["bedrooms"],
                    "beds_number": listing["beds"],
                    "bathrooms_number": listing["bathrooms"],
                    "city": listing["city"],
                    "country": listing["country"],
                    "country_code": listing["country_code"],
                    "currency_code": listing["currency"],
                    "average_review_rating": listing["rating"],
                    "hostaway_special_status": "",
                    "min_nights": 1,
                    "max_nights": 365,
                    "check_in_time_start": 15,
                    "check_out_time": 12,
                    "instant_bookable": True,
                    "time_zone_name": "Africa/Casablanca" if listing["country_code"] == "MA" else "Asia/Riyadh",
                    "slug": listing["slug"],
                    "name_ar": listing["name_ar"],
                    "name_en": listing["name_en"],
                    "name_fr": listing["name_fr"],
                    "short_description_ar": listing["short_ar"],
                    "short_description_en": listing["short_en"],
                    "short_description_fr": listing["short_fr"],
                    "description_ar": listing["short_ar"],
                    "description_en": listing["short_en"],
                    "description_fr": listing["short_fr"],
                    "city_ar": "مراكش" if listing["country_code"] == "MA" else "الرياض",
                    "city_en": listing["city"],
                    "city_fr": "Marrakech" if listing["country_code"] == "MA" else "Riyad",
                    "is_visible": True,
                    "visibility_management": Property.VisibilityManagement.MANUAL,
                    "is_featured": index <= 3,
                    "sort_order": index,
                },
            )
            created_properties += int(created)
            _image, image_created = PropertyImage.objects.update_or_create(
                hostaway_image_id=listing["image_id"],
                defaults={
                    "property": property_obj,
                    "hostaway_url": listing["image_url"],
                    "source": PropertyImage.Source.HOSTAWAY,
                    "title_ar": listing["name_ar"],
                    "title_en": listing["name_en"],
                    "title_fr": listing["name_fr"],
                    "alt_text_ar": listing["name_ar"],
                    "alt_text_en": listing["name_en"],
                    "alt_text_fr": listing["name_fr"],
                    "sort_order": 1,
                    "hostaway_sort_order": 1,
                    "is_cover": True,
                    "is_city_hero": listing["city_hero"],
                    "is_visible": True,
                    "is_active_at_source": True,
                },
            )
            created_images += int(image_created)

        self.stdout.write(
            self.style.SUCCESS(
                "Staging catalogue ready: "
                f"properties_created={created_properties}, images_created={created_images}, "
                f"total_listings={len(LISTINGS)}."
            )
        )
