"""Guest-account copy kept together across the three supported languages."""

from django.utils.translation import get_language

ACCOUNT_COPY = {
    "en": {
        "welcome": "Welcome",
        "welcome_named": "Hello, %(name)s",
        "welcome_back": "Welcome back",
        "last_login": "Last sign-in",
        "bookings": "My bookings",
        "rewards": "My rewards",
        "details": "My details",
        "navigation": "Your account",
        "upcoming": "Upcoming & current",
        "past": "Previous",
        "cancelled": "Cancelled",
        "empty_upcoming": "No upcoming bookings",
        "empty_past": "No previous stays yet",
        "empty_cancelled": "No cancelled bookings",
        "empty_hint": "Choose your accommodation and dates for your next stay.",
        "choose_stay": "Choose your next stay",
        "missing_booking": "Is a booking missing here?",
        "access_booking": "Manage an existing booking",
        "access_hint": "Open your booking using a secure link sent to your booking email.",
        "support": "We are here to help",
        "contact": "Contact us",
        "privacy": "Privacy",
        "sign_out": "Sign out",
        "coming_soon": "Coming soon",
        "rewards_heading": "Our loyalty programme is on its way",
        "rewards_intro": "We are preparing a rewards programme with our guests in mind.",
        "rewards_hint": "Programme details will appear here after launch.",
        "return_bookings": "Back to my bookings",
        "personal": "Personal details",
        "first_name": "First name",
        "last_name": "Last name",
        "communication": "Contact details",
        "email": "Email",
        "verified": "Verified",
        "not_verified": "Not yet verified",
        "verify_email": "Verify my email",
        "phone": "Mobile number",
        "phone_example": "For example: +966 50 000 0000",
        "preferences": "Account preferences",
        "language": "Preferred language",
        "current_language": "Use the current website language",
        "arabic": "Arabic",
        "english": "English",
        "french": "French",
        "address": "Address — optional",
        "address_hint": "An address is not required to use your account.",
        "country": "Country",
        "city": "City",
        "address_more": "Additional address details",
        "street": "Street address",
        "region": "Region",
        "postal": "Postal code",
        "account_info": "Account information",
        "signin_methods": "Sign-in options",
        "email_code": "Email verification code",
        "save": "Save changes",
        "saved": "Your changes have been saved.",
        "email_protected": (
            "Your sign-in email is protected. Changing it requires verifying the new address."
        ),
        "form_errors": "Please review the highlighted fields.",
        "previous_page": "Previous page",
        "next_page": "Next page",
        "page": "Page",
        "of": "of",
    },
    "ar": {
        "welcome": "مرحبًا بك",
        "welcome_named": "مرحبًا، %(name)s",
        "welcome_back": "سعداء بعودتك",
        "last_login": "آخر تسجيل دخول",
        "bookings": "حجوزاتي",
        "rewards": "مكافآتي",
        "details": "بياناتي",
        "navigation": "حسابك",
        "upcoming": "القادمة والحالية",
        "past": "السابقة",
        "cancelled": "الملغاة",
        "empty_upcoming": "لا توجد حجوزات قادمة",
        "empty_past": "لا توجد إقامات سابقة بعد",
        "empty_cancelled": "لا توجد حجوزات ملغاة",
        "empty_hint": "اختر مكان إقامتك وتواريخك لإقامتك القادمة.",
        "choose_stay": "اختر إقامتك القادمة",
        "missing_booking": "لديك حجز لا يظهر هنا؟",
        "access_booking": "إدارة حجز قائم",
        "access_hint": "افتح حجزك عبر رابط آمن يُرسل إلى بريد الحجز.",
        "support": "نحن هنا لمساعدتك",
        "contact": "تواصل معنا",
        "privacy": "الخصوصية",
        "sign_out": "تسجيل الخروج",
        "coming_soon": "قريبًا",
        "rewards_heading": "برنامج الولاء قيد التجهيز",
        "rewards_intro": "نعمل على تجهيز برنامج مكافآت يليق بضيوفنا.",
        "rewards_hint": "ستظهر تفاصيل البرنامج هنا بعد إطلاقه.",
        "return_bookings": "العودة إلى حجوزاتي",
        "personal": "البيانات الشخصية",
        "first_name": "الاسم الأول",
        "last_name": "اسم العائلة",
        "communication": "بيانات التواصل",
        "email": "البريد الإلكتروني",
        "verified": "تم التحقق",
        "not_verified": "لم يتم التحقق بعد",
        "verify_email": "تأكيد بريدي الإلكتروني",
        "phone": "رقم الجوال",
        "phone_example": "+966 50 000 0000",
        "preferences": "تفضيلات الحساب",
        "language": "اللغة المفضلة",
        "current_language": "استخدام لغة الموقع الحالية",
        "arabic": "العربية",
        "english": "الإنجليزية",
        "french": "الفرنسية",
        "address": "العنوان — اختياري",
        "address_hint": "العنوان ليس شرطًا لاستخدام حسابك.",
        "country": "الدولة",
        "city": "المدينة",
        "address_more": "تفاصيل إضافية للعنوان",
        "street": "الشارع والعنوان",
        "region": "المنطقة",
        "postal": "الرمز البريدي",
        "account_info": "معلومات الحساب",
        "signin_methods": "خيارات تسجيل الدخول",
        "email_code": "رمز التحقق بالبريد الإلكتروني",
        "save": "حفظ التغييرات",
        "saved": "تم حفظ التغييرات بنجاح.",
        "email_protected": "بريد تسجيل الدخول محمي؛ تغييره يتطلب التحقق من البريد الجديد.",
        "form_errors": "يرجى مراجعة الحقول الموضّحة أدناه.",
        "previous_page": "الصفحة السابقة",
        "next_page": "الصفحة التالية",
        "page": "صفحة",
        "of": "من",
    },
    "fr": {
        "welcome": "Bienvenue",
        "welcome_named": "Bonjour, %(name)s",
        "welcome_back": "Ravis de vous retrouver",
        "last_login": "Dernière connexion",
        "bookings": "Mes réservations",
        "rewards": "Mes avantages",
        "details": "Mes informations",
        "navigation": "Votre compte",
        "upcoming": "À venir et en cours",
        "past": "Passées",
        "cancelled": "Annulées",
        "empty_upcoming": "Aucune réservation à venir",
        "empty_past": "Aucun séjour précédent",
        "empty_cancelled": "Aucune réservation annulée",
        "empty_hint": "Choisissez votre hébergement et vos dates pour votre prochain séjour.",
        "choose_stay": "Choisir mon prochain séjour",
        "missing_booking": "Une réservation manque ici ?",
        "access_booking": "Gérer une réservation existante",
        "access_hint": (
            "Accédez à votre réservation via un lien sécurisé envoyé à son adresse e-mail."
        ),
        "support": "Nous sommes là pour vous aider",
        "contact": "Nous contacter",
        "privacy": "Confidentialité",
        "sign_out": "Déconnexion",
        "coming_soon": "Bientôt",
        "rewards_heading": "Notre programme de fidélité se prépare",
        "rewards_intro": "Nous préparons un programme de récompenses pensé pour nos hôtes.",
        "rewards_hint": "Les détails du programme seront disponibles ici après son lancement.",
        "return_bookings": "Retour à mes réservations",
        "personal": "Informations personnelles",
        "first_name": "Prénom",
        "last_name": "Nom de famille",
        "communication": "Coordonnées",
        "email": "Adresse e-mail",
        "verified": "Vérifiée",
        "not_verified": "Pas encore vérifiée",
        "verify_email": "Vérifier mon adresse e-mail",
        "phone": "Numéro de mobile",
        "phone_example": "Par exemple : +966 50 000 0000",
        "preferences": "Préférences du compte",
        "language": "Langue préférée",
        "current_language": "Utiliser la langue actuelle du site",
        "arabic": "Arabe",
        "english": "Anglais",
        "french": "Français",
        "address": "Adresse — facultative",
        "address_hint": "L’adresse n’est pas nécessaire pour utiliser votre compte.",
        "country": "Pays",
        "city": "Ville",
        "address_more": "Complément d’adresse",
        "street": "Adresse et rue",
        "region": "Région",
        "postal": "Code postal",
        "account_info": "Informations du compte",
        "signin_methods": "Options de connexion",
        "email_code": "Code de vérification par e-mail",
        "save": "Enregistrer les modifications",
        "saved": "Vos modifications ont été enregistrées.",
        "email_protected": (
            "Votre adresse de connexion est protégée. "
            "Toute modification nécessite de vérifier la nouvelle adresse."
        ),
        "form_errors": "Veuillez vérifier les champs indiqués ci-dessous.",
        "previous_page": "Page précédente",
        "next_page": "Page suivante",
        "page": "Page",
        "of": "sur",
    },
}


def account_copy(language: str = "") -> dict[str, str]:
    language = (language or get_language() or "ar").split("-")[0]
    return ACCOUNT_COPY.get(language, ACCOUNT_COPY["ar"])
