# Generated by Django 5.2.16 on 2026-07-29 22:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hostaway_review_id", models.PositiveBigIntegerField(unique=True)),
                (
                    "hostaway_listing_map_id",
                    models.PositiveBigIntegerField(db_index=True),
                ),
                (
                    "hostaway_reservation_id",
                    models.CharField(blank=True, max_length=100),
                ),
                ("external_review_id", models.CharField(blank=True, max_length=150)),
                ("channel_id", models.CharField(blank=True, max_length=100)),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("guest-to-host", "ضيف إلى مضيف"),
                            ("host-to-guest", "مضيف إلى ضيف"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("published", "منشورة"),
                            ("awaiting", "قيد الانتظار"),
                            ("declined", "مرفوضة"),
                            ("other", "أخرى"),
                        ],
                        max_length=30,
                    ),
                ),
                ("guest_name", models.CharField(blank=True, max_length=200)),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("10")),
                        ],
                    ),
                ),
                ("public_review", models.TextField()),
                ("reviewee_response", models.TextField(blank=True)),
                ("arrival_date", models.DateField(blank=True, null=True)),
                ("departure_date", models.DateField(blank=True, null=True)),
                ("is_visible", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
                ("synced_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "مراجعة",
                "verbose_name_plural": "المراجعات",
                "ordering": ["-is_featured", "-departure_date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["property", "-departure_date"],
                        name="reviews_rev_propert_9332c1_idx",
                    ),
                    models.Index(
                        fields=["status", "review_type"],
                        name="reviews_rev_status_9027d0_idx",
                    ),
                    models.Index(
                        fields=["rating"], name="reviews_rev_rating_2db6dd_idx"
                    ),
                    models.Index(
                        fields=["is_visible", "is_featured"],
                        name="reviews_rev_is_visi_056f87_idx",
                    ),
                    models.Index(
                        fields=["-departure_date"],
                        name="reviews_rev_departu_978018_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("rating__gte", 0), ("rating__lte", 10)),
                        name="review_rating_between_0_and_10",
                    )
                ],
            },
        ),
    ]
