# Generated by Django 5.2.16 on 2026-07-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="public_review_ar",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="review",
            name="public_review_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="review",
            name="public_review_fr",
            field=models.TextField(blank=True),
        ),
    ]
