# Generated by Django 5.2.16 on 2026-09-03 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_review_public_review_ar_review_public_review_en_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ["-is_featured", "-departure_date", "-id"],
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
            },
        ),
    ]
