# Generated by Django 5.2.16 on 2026-09-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_alter_review_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="review_type",
            field=models.CharField(
                choices=[
                    ("guest-to-host", "Guest to host"),
                    ("host-to-guest", "Host to guest"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Published"),
                    ("awaiting", "Pending"),
                    ("declined", "Rejected"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
