# Generated by Django 5.2.16 on 2026-07-30 22:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message_type", models.CharField(max_length=80)),
                ("recipient_hash", models.CharField(editable=False, max_length=64)),
                ("recipient_masked", models.CharField(editable=False, max_length=254)),
                ("recipient_source", models.CharField(editable=False, max_length=40)),
                (
                    "recipient_reference",
                    models.CharField(editable=False, max_length=100),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("ar", "العربية"), ("en", "English")], max_length=10
                    ),
                ),
                ("subject", models.CharField(max_length=250)),
                ("template_name", models.CharField(max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "في الطابور"),
                            ("sending", "قيد الإرسال"),
                            ("sent", "مرسل"),
                            ("failed", "فشل"),
                            ("cancelled", "ملغى"),
                            ("skipped", "متجاوز"),
                            ("disabled", "معطل"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(max_length=80)),
                (
                    "provider_message_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("idempotency_key", models.CharField(max_length=100, unique=True)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("last_error_code", models.CharField(blank=True, max_length=100)),
                ("queued_at", models.DateTimeField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "تسليم بريد",
                "verbose_name_plural": "تسليمات البريد",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "queued_at"],
                        name="notificatio_status_fe6c27_idx",
                    ),
                    models.Index(
                        fields=["message_type", "-created_at"],
                        name="notificatio_message_93ff00_idx",
                    ),
                    models.Index(
                        fields=["recipient_hash", "-created_at"],
                        name="notificatio_recipie_a68440_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("object_type", models.CharField(max_length=100)),
                ("object_reference", models.CharField(max_length=100)),
                ("summary", models.CharField(max_length=300)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "ip_hash",
                    models.CharField(
                        blank=True, editable=False, max_length=64, null=True
                    ),
                ),
                ("user_agent_family", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تدقيق",
                "verbose_name_plural": "سجلات التدقيق",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "-created_at"],
                        name="notificatio_action_b71cd9_idx",
                    ),
                    models.Index(
                        fields=["object_type", "object_reference"],
                        name="notificatio_object__4838aa_idx",
                    ),
                    models.Index(
                        fields=["actor_user", "-created_at"],
                        name="notificatio_actor_u_01fb87_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="notificatio_created_8beff0_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("contact_message_received", "رسالة تواصل"),
                            ("booking_intent_created", "طلب حجز"),
                            ("booking_price_changed", "تغير السعر"),
                            ("booking_unavailable", "الوحدة غير متاحة"),
                            ("modification_requested", "طلب تعديل"),
                            ("cancellation_requested", "طلب إلغاء"),
                            ("hostaway_sync_failed", "فشل مزامنة"),
                            ("webhook_failed", "فشل Webhook"),
                            ("reservation_unknown", "حجز غير مؤكد"),
                            ("system_warning", "تحذير نظام"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "audience_type",
                    models.CharField(
                        choices=[("admin", "الإدارة"), ("user", "مستخدم")],
                        max_length=20,
                    ),
                ),
                ("title_ar", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200)),
                ("message_ar", models.CharField(max_length=500)),
                ("message_en", models.CharField(max_length=500)),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Action URL must be a relative internal path.",
                                regex="^/(?!/)[^\\s]*$",
                            )
                        ],
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "معلومة"),
                            ("success", "نجاح"),
                            ("warning", "تحذير"),
                            ("error", "خطأ"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "نشط"), ("archived", "مؤرشف")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("related_object_type", models.CharField(blank=True, max_length=80)),
                (
                    "related_object_reference",
                    models.CharField(blank=True, max_length=100),
                ),
                ("idempotency_key", models.CharField(max_length=100, unique=True)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operational_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "إشعار",
                "verbose_name_plural": "الإشعارات",
                "ordering": ["-created_at"],
                "permissions": [
                    ("manage_notification_center", "Can manage notification center")
                ],
                "indexes": [
                    models.Index(
                        fields=["status", "is_read", "-created_at"],
                        name="notificatio_status_bfc0a7_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "-created_at"],
                        name="notificatio_notific_d8746a_idx",
                    ),
                    models.Index(
                        fields=["recipient_user", "is_read", "-created_at"],
                        name="notificatio_recipie_0e7d23_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="notificatio_expires_4f3289_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("audience_type", "admin"),
                            ("recipient_user__isnull", False),
                            _connector="OR",
                        ),
                        name="user_notification_requires_recipient",
                    )
                ],
            },
        ),
    ]
