# Generated by Django 5.2.16 on 2026-07-31 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaildelivery",
            name="language",
            field=models.CharField(
                choices=[("ar", "العربية"), ("en", "English"), ("fr", "Français")],
                max_length=10,
            ),
        ),
    ]
