# Generated by Django 5.2.16 on 2026-09-03 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_emaildelivery_language"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Audit log entry",
                "verbose_name_plural": "Audit log entries",
            },
        ),
        migrations.AlterModelOptions(
            name="emaildelivery",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Email delivery",
                "verbose_name_plural": "Email deliveries",
            },
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("manage_notification_center", "Can manage notification center")
                ],
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
    ]
