# Generated by Django 5.2.16 on 2026-09-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0003_alter_auditlog_options_alter_emaildelivery_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaildelivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("sending", "Sending"),
                    ("sent", "Sent"),
                    ("failed", "Failure"),
                    ("cancelled", "Cancelled"),
                    ("skipped", "Superseded"),
                    ("disabled", "Disabled"),
                ],
                default="queued",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="audience_type",
            field=models.CharField(
                choices=[("admin", "Administration"), ("user", "Used")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("contact_message_received", "Contact message"),
                    ("booking_intent_created", "Booking request"),
                    ("booking_price_changed", "Price changed"),
                    ("booking_unavailable", "Property unavailable"),
                    ("modification_requested", "Modification request"),
                    ("cancellation_requested", "Cancellation request"),
                    ("hostaway_sync_failed", "Sync failure"),
                    ("webhook_failed", "Webhook failure"),
                    ("reservation_unknown", "Unconfirmed booking"),
                    ("system_warning", "System warning"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="severity",
            field=models.CharField(
                choices=[
                    ("info", "Info"),
                    ("success", "Success"),
                    ("warning", "Warning"),
                    ("error", "Error"),
                ],
                default="info",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("archived", "Archived")],
                default="active",
                max_length=20,
            ),
        ),
    ]
