# Generated by Django 5.2.16 on 2026-09-18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_notification_type_refund_due"),
        ("reservations", "0016_manual_draft_booked_awaiting_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message_type", models.CharField(max_length=80)),
                ("recipient_masked", models.CharField(editable=False, max_length=40)),
                ("recipient_reference", models.CharField(editable=False, max_length=100)),
                ("provider", models.CharField(default="ultramsg", editable=False, max_length=80)),
                ("provider_message_id", models.CharField(blank=True, editable=False, max_length=255)),
                ("idempotency_key", models.CharField(editable=False, max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("failed", "Failure"),
                            ("disabled", "Disabled"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("last_error_code", models.CharField(blank=True, max_length=100)),
                ("queued_at", models.DateTimeField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reservation",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounting_whatsapp_delivery",
                        to="reservations.reservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp delivery",
                "verbose_name_plural": "WhatsApp deliveries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "queued_at"], name="notificatio_status_69cfed_idx"
                    ),
                    models.Index(
                        fields=["message_type", "-created_at"], name="notificatio_message_3a6671_idx"
                    ),
                ],
            },
        ),
    ]
