# Generated by Django 5.2 on 2026-09-18

from django.db import migrations, models
from django.db.models import Q, deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_whatsappdelivery"),
        ("reservations", "0016_manual_draft_booked_awaiting_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatsappdelivery",
            name="reservation",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=deletion.PROTECT,
                related_name="accounting_whatsapp_delivery",
                to="reservations.reservation",
            ),
        ),
        migrations.AddField(
            model_name="whatsappdelivery",
            name="modification_request",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=deletion.PROTECT,
                related_name="accounting_whatsapp_delivery",
                to="reservations.bookingmodificationrequest",
            ),
        ),
        migrations.AddConstraint(
            model_name="whatsappdelivery",
            constraint=models.CheckConstraint(
                condition=Q(reservation__isnull=False) | Q(modification_request__isnull=False),
                name="whatsapp_delivery_has_subject",
            ),
        ),
    ]
